// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_UXCLGdi91MgdW0O34NUWwETFL-aldQc',
    appId: '1:314086732361:android:29023b61f5f2f4e26f4598',
    messagingSenderId: '314086732361',
    projectId: 'student-media-taufeeq',
    storageBucket: 'student-media-taufeeq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1rzxa5ck0MjdDFhGDb1aBpJvKi_XaBTs',
    appId: '1:314086732361:ios:27fd2ab188aa0e1e6f4598',
    messagingSenderId: '314086732361',
    projectId: 'student-media-taufeeq',
    storageBucket: 'student-media-taufeeq.appspot.com',
    iosClientId: '314086732361-e9pnanvu08bc0g9dpdk9shggtf425qrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentMedia',
  );
}
